name: db2
services:
  db2:
    image: ibmcom/db2:latest
    platform: linux/amd64
    privileged: true
    container_name: db2
    environment:
      - LICENSE=accept
      - DB2INSTANCE=db2inst1
      - DB2INST1_PASSWORD=password
      - DBNAME=testdb
      - BLU=false
      - ENABLE_ORACLE_COMPATIBILITY=false
      - UPDATEAVAIL=NO
      - TO_CREATE_SAMPLEDB=false
      - REPODB=false
      # true solo en MacOS
      - IS_OSXFS=true
      # false solo en windows
      - PERSISTENT_HOME=true
      - HADR_ENABLED=false
      # - ETCD_ENDPOINT= 
      # - ETCD_USERNAME= Idem DB2Instance
      # - ETCD_PASSWORD= Idem DB2Inst password
    volumes:
      # Colocar su nombre de usuario
      - /Users/<username>/Docker:/database icr.io/db2_community/db2
      - ../backups:/backups
    ports:
      - "50000:50000"